name: built_redux_rx
version: 0.1.3
description:
   epics for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_rx
dependencies:
  built_redux: ^7.5.0
  built_value: ^7.1.0
  rxdart: ^0.24.1

dev_dependencies:
  #build_runner: ^0.10.0
  #build_test: ^0.10.0
  built_value_generator: ^7.1.0
  #build_web_compilers: ^0.4.0
  test: any

environment:
  sdk: '>=2.0.0-dev <3.0.0'